### ISSUE TITLE
[EPIC] Mergeable Spec

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/troubleshoot#650]
### Problem
Troubleshoot doesn't have a modular way for different components to specify specifications. If a software project wanted to include project specific items the end user would have a hard time knowing where to find those and how to collect them. Furthermore if multiple projects were to do this the user would have to run troubleshoot multiple times.

Ideally troubleshoot would allow merging of specs to allow building a spec either automatically or influenced by user input to target specific needs.

### Proposal
Add the ability for troubleshoot to merge specs and deal with combining overlapping configurations to build one master spec. This should allow any of the input specifications to build up a list of specs that are then merged for the final specification. The final specification should be included in the final bundle.

### Definition of done
* Ability for troubleshoot to merge specs
* Tests added to verify the merge works including edge cases where combining is not straight forward
* Documentation added explaining how merging works

### Started

- [x] https://github.com/replicatedhq/troubleshoot/issues/663
- [x] https://github.com/replicatedhq/troubleshoot/issues/665
- [x] https://github.com/replicatedhq/troubleshoot/issues/680
- [x] #699
- [x] Support multiple Redactor specs from the CLI

### Planned

- [x] #713
- [ ] de-deuplicate Redactor specs (Redactor is already an Interface in package `redact`)
- [ ] Switch `troubleshootv1beta2.Analyze`to Interface

**Comment by chris-sanders** [comment]
Documenting some discussion from today for broader review.

It's unclear if "merging" really needs to mean anything more than deduplicating. Even deduplicating might be an optimization for reducing runtime that has little affect on the final outcome. As an example, if logs are collected twice for the same pod the logs will still be present but collection may incrementally increase because the API call is made twice to get the same information.

While ideally these duplicate issues would be reduced it may not be necessary in a first implementation to address explicitly for all collectors. Having said that, the current proposal is to consider adding the merge logic at the collector level. Ideally there would be a default "Merge" function that does nothing more than append all of the values into a single file with no merging or deduplication. Collectors can then each implement a collector specific merge to override the default if 'merging' has value for that particular collector. This also lets merge logic be scoped to specific collectors where the decision to append, merge, or deduplicate can be made knowing the context of what is being collected.

Some examples to help clarify this.
* Two runPod collectors with the same name and different commands are unmergable. Only one should be run and an error logged.
* Two configMap collectors can be deduplicated and merged depending on the configurations
* Two logs collectors likely only need deduplication to prevent collecting the same thing twice

**Comment by chris-sanders** [comment]
- [ ] This is a test task

**Comment by xavpaice** [comment]
PR for the design doc: https://github.com/replicatedhq/troubleshoot/pull/662

**Comment by xavpaice** [comment]
I'm closing this epic since we now have met the criteria for 'done'.  Deduplicating Redactors, plus moving Analyze to an interface should really be out of scope and I'm happy to let them go to a more appropriate epic in future when we even define the scope of those tasks.
