### ISSUE TITLE
Add URI type to spec definition

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#682]
Add a new field to the Troubleshoot spec definition, will enable a URI to be used to locate another spec.

In PR https://github.com/replicatedhq/troubleshoot/pull/681 we describe using a new field in the Troubleshoot spec definition to allow a URI to be specified for a replacement (i.e. updated) spec for the spec provided.

The spec URI listed should be any valid location that Troubleshoot can accept on the CLI - this could be a secret, file, or an address.

This particular task is to update the CRDs so that when a spec is provided to Troubleshoot, it can include a new field per the example below.

Current spec format is like this example:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: default
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
  analyzers:
    - cephStatus: {}
    - longhorn: {}
```

We could add a new type, `uri` under the top level spec, which contains a list of URIs from which to obtain specs:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: default
spec:
  uri: https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/in-cluster/default.yaml
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
  analyzers:
    - cephStatus: {}
    - longhorn: {}
```

In scope:

* adding the ability to accept the new data without error

Out of scope:

* doing anything with that new data

Definition of done:

- [x] Troubleshoot can accept a spec yaml with the second format provided above, without error
- [x] Any tests which validate spec definition are updated (or written)
- [x] A draft (but not available online) document detailing the required format

**Comment by chris-sanders** [comment]
I mentioned this on the design doc, but since we're going to run a bit ahead and start on this I'll say it here as well.

I think we should just use `uri` instead of `specURI` because the full path as shown above is `spec.specURI` which is repetitive.

**Comment by edgarlanting** [comment]
On todays CRE team call we pretty much agreed to use `uri` to minimize stuttering amongst others. So for example; instead of `spec`.`specURI` we'd want to use `spec`.`uri`

**Comment by edgarlanting** [comment]
`./cmd/schemagen/cli/root.go` generates a new schema in `./schemas`.

These are:

`analyzer-troubleshoot-v1beta2.json`
`preflight-troubleshoot-v1beta2.json`
`supportbundle-v1beta2.json`

Initially, the idea and understanding was that we can add the additional `uri` property to the CRD over at `./config/crds/troubleshoot.sh-supportbundles..yaml`, however, when one runs `make schemas` this reverts the changes and and the `uri` change will be lost.

The actual location where we need to add the new type (as its not just a new property of the top level spec, but also a new type) is in `./pkg/apis/troubleshoot/v1beta2/supportbundle_types.go` as:

```
Uri             string             `json:"uri,omitempty" yaml:"uri,omitempty"`
```

This id then propagated into a freshly generated schema:
![Screenshot 2022-08-31 at 15 22 10](https://user-images.githubusercontent.com/5877847/187688725-b9d9574d-1588-4b40-b88d-d7dfa93f9dfc.png)


This lets you run a `make schemas` and recreate the correctly populated schema file for Troubleshoot.

Next steps:

1)- Add URI to types.
~2)- Add functionality to use URI~
3)- Add tests
4)- Add documentation

**Comment by chris-sanders** [comment]
@edgarlanting just a note, you can skip step 2 above at this stage. Just add tests and documentation for what the field is and verify that we don't break backwards compatibility with old clients if they get a new bundle type.

If you check #685 you'll see there are follow up tasks to add the CLI bits to use the URI field and to disable its use. We're running  bit ahead by starting on this task while the epic is being defined.

**Comment by edgarlanting** [comment]
When talking about `Troubleshoot can accept a spec yaml with the second format provided above, without error` in the "**definition of done**", this more sounds like building in the actual logic to work with another uri field. I would think this belongs more to #685 where we build in the working parts. What do you think @chris-sanders @xavpaice? 

For the rest;

- Backward compatibility has been manually tested with older versions: v0.34.0 (May 2022 - arm64 & amd64), v0.28.1 (January 2022 - arm64 & amd64) and v0.13.14 (September 2021 - amd64) and a 'new' spec:

```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: default
spec:
  uri: https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/in-cluster/default.yaml
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
  analyzers:
    - cephStatus: {}
    - longhorn: {}
```

- Regarding documentation; Do we have existing documentation available for all current fields, and since this needs to be a draft, where should this reside? I have tried to find this however it looks like there is no such thing.

For now, I've added a comment in `troubleshoot.sh_supportbundles.yaml`:

```
// Uri defines the location of the spec file that needs to be used. This is optional and can be 
// either a secret, url or spec yaml file.
// When presented with a spec document that contains a URI, if that spec is one of the specs provided 
// on the command line or initial call to Troubleshoot, attempt to collect a replacement spec from that URI. 
// If successful, it will replace the entire spec with the one downloaded. 
// If unsuccessful, log the error and use the spec provided.
	Uri             string             `json:"uri,omitempty" yaml:"uri,omitempty"`
}
```

In case we're complete in terms of this issue, the PR is over at #696

**Comment by chris-sanders** [comment]
@edgarlanting, the comment about the format is meant to cover backwards compatibility. I'm glad you manually tested it be sure to include your test steps and output demonstrating it on the PR with the change. Ideally, it would be interesting if you would give some thought to how you could verify that with a test rather than by hand. It would be useful to have a test which verifies, in some fashion, that we haven't broken backwards compatibility when we add new fields or types to the scheme.

As for documentation, the actual website is in the repo https://github.com/replicatedhq/troubleshoot.sh maybe that has a spot or could have a good spot to do it? I like the idea of starting to add more in-code comments let's be sure to review [godoc guidelines](https://go.dev/blog/godoc) for proper standards and formatting if we choose to use it in the future.

I commented on the actual PR so see there for comments about the doc string itself.

**Comment by xavpaice** [comment]
The tasks in this might not be particularly well written given that the testing done so far would make the first bullet pass without any changes to the repo at all, but with PR #696 I think that's got both goals in here.

I'd like to see a docs PR, but that should be part of #694, not this change.

If there are tests we can add to verify that the updated schema doesn't cause regressions with older versions (i.e. the most recent release), then this is a good opportunity to add the test.  Likely this is a Github workflow type of test rather than within the Go code itself.

**Comment by edgarlanting** [comment]
Thanks both @chris-sanders and @xavpaice for your feedback on this. I will see to think about any useful ways we can include an actual test for this new field apart from the manual testing I've done.

**Comment by chris-sanders** [comment]
> If there are tests we can add to verify that the updated schema doesn't cause regressions with older versions (i.e. the most recent release), then this is a good opportunity to add the test. Likely this is a Github workflow type of test rather than within the Go code itself.

I'll add to this, in case you aren't aware, there is a URL which references assets on a release. One option for that URL is to use the 'latest' release, which is how I suspect you would implement such a test. Download the current latest release and check that it doesn't error when run against the example from this branch. Ref: https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

**Comment by adamancini** [comment]
@xavpaice @chris-sanders do we want the `uri:` field to support multiple URIs?  

thinking either something like:


```
spec:
  uri: https://foo.bar.com/suppbundle.yaml
  uri: https://foo.bar.com/suppbundle2.yaml
  ...
```

or

```
spec:
  uri:
    - https://foo.bar.com/suppbundle.yaml
    - https://foo.bar.com/suppbundle2.yaml
    - ...
```


talking with Edgar we kind of leaning towards the latter, since it looks consistent with `analyzers:` and `collectors:`

**Comment by xavpaice** [comment]
@adamancini we originally talked about having multiple as a list, however this wasn't selected as it would be confusing since the remainder of the spec is read if the download fails - i.e., if we have 4 URIs, two download OK and two fail, do we read the spec in the file or not... so we decided to have just the one URI for this, and if we wanted to have multiple we could supply multiple yaml specs each with a URI.

**Comment by xavpaice** [comment]
With the change merged, I'm closing this task as done, the change added an example for usage, but we can't put real docs online till #699 is completed.  There's no tests, but this is a data change for an external package so I think we can manage without.
