### ISSUE TITLE
[Epic] Updatable specs

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/troubleshoot#685]
# Design Proposal

Available in [design folder](https://github.com/replicatedhq/troubleshoot/blob/main/design/proposal-updateable-specs.md)

# Definition of done

* [x] Documentation updated to include how to enable feature and how it's useful
* [ ] At least one test that verifies updates work as intended
* [x] Specs have a way to be updated at runtime by Troubleshoot

# Subtasks

## Started

* [x] #682 
* [x] #694 
* [x] #695
* [x] #759 

## Planned

* [x] #712
* [x] #716
* [x] #711

**Comment by xavpaice** [comment]
last item is the tests, which have a tracking issue.  Closing as we won't focus on this now.
