### ISSUE TITLE
[Epic] Mergeable preflight specs

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#859]
# Design Proposal

Link to the [proposal](https://github.com/replicatedhq/troubleshoot/pull/858)

# Definition of done

Describe what specific goals can measure if this overall task is considered completed. Things to consider are documentation, high level description of the feature working, and tests.

* [x] ADR agreed and merged
* [x] Preflight checks binary accepts (and processes) multiple specs on the command line
* [x] Preflight package accepts multiple specs when called
* [x] All changes have tests
* [ ] Documentation on troubleshoot.sh is updated

# Subtasks

Create a list of the smaller tasks to implement this design. Task can start as simple descriptions but should be converted to issues before work is started.

## Started

* [x] #860

## Planned

* [x] #861
* [x] #832 
* [ ] Docs: preflight docs in troubleshoot.sh updated to note that multiple specs can be supplied on the CLI
* [ ] Plans: kURL calls preflight with individual specs per add-on

**Comment by diamonwiggins** [comment]
Hasn't been released yet, but https://github.com/replicatedhq/troubleshoot/pull/832 satisfies the addition of `merge/dedup` functionality for preflight.

With regards to:

> Plans: kURL calls preflight with individual specs per add-on

kURL more or less behaves like this already afaik. It runs host preflights with the following command:

`/var/lib/kurl/bin/kurl host preflight <installer-spec.yaml>`

It templates over https://github.com/replicatedhq/kURL/blob/main/pkg/preflight/assets/host-preflights.yaml as well as the other `host-preflight.yaml` files found per addon. For example [Weave](https://github.com/replicatedhq/kURL/blob/main/addons/weave/2.8.1/host-preflight.yaml)

In order to move this functionality out of kURL and into preflight, we'd need the ability to template

**Comment by xavpaice** [comment]
Closing: the docs changes are out of scope here because there is in fact no documentation for the Preflight CLI at all.  We will complete that with #933.
