### ISSUE TITLE
[Epic] Consolidation of sbctl and Troubleshoot repos

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#882]
# Overview

Currently there are two repos, one for sbctl and one for Troubleshoot.  This task is to consolidate the sbctl code into Troubleshoot, with the following broad goals:

* Reduce code duplication
* make sbctl more available to users of Troubleshoot
* allow analyzers the option to use sbctl for getting data (rather than raw results or support bundle info)

# Design Proposal

* [x] replicatedhq/troubleshoot#884

# Definition of done

Describe what specific goals can measure if this overall task is considered completed. Things to consider are documentation, high level description of the feature working, and tests.

* [ ] sbctl repo is deprecated, and all the code is moved to Troubleshoot
* [ ] Docs have been updated

# Subtasks

Create a list of the smaller tasks to implement this design. Task can start as simple descriptions but should be converted to issues before work is started.

## Started

* [ ]

## Planned

* [x] replicatedhq/troubleshoot#960
* [ ] Document the use of sbctl as a CLI tool in troubleshoot.sh
* [x] replicatedhq/sbctl#72
* [x] #962
* [ ] merge sbctl repo into troubleshoot
* [ ] add a localhost api listener and client for analyzers to import
* [ ] add one analyzer using the k8s api via sbctl
* [ ] Troubleshoot/sbctl code deduplication and consolidation
* [ ] add test coverage
